name: pcb_image
on:
  push:
jobs:
  generate-pages:
    name: generate-pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install interactive HTML BOM
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-9.0-releases
          sudo apt update
          sudo apt install --install-recommends kicad libgtk-3-dev
          sudo python -m pip install InteractiveHtmlBom
      
      - name: Generate interactive HTML BOM
        run: |
          mkdir images
          kicad-cli pcb render --side top --output images/top.png keymatrix.kicad_pcb
          kicad-cli pcb render --side bottom --output images/bottom.png keymatrix.kicad_pcb
          INTERACTIVE_HTML_BOM_NO_DISPLAY=true generate_interactive_bom keymatrix.kicad_pcb
          mkdir pages
          mv bom images pages
      
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "pages"

  deploy-pages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: generate-pages
      
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
